version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:176275544602:task-definition/digi-pms-pp-td:1"
        LoadBalancerInfo:
          ContainerName: "digi-pms-pp-container"
          ContainerPort: "9002"
        PlatformVersion: "LATEST"